### ISSUE TITLE
Add "UI Uptime" widget

### ISSUE THREAD

**Issue by bruceywang** [Brightergy/ex_gecko#19]
Use the same "API Uptime" widget, but instead use the UI smoke test instead (this is in runscope, which just runs ghost inspector)

**Comment by njdu** [comment]
@bruceywang @erik-jenkins Erik has been working on generalizing some of the old runscope adapter code, so that it will work with any widget key. That will address this issue.

**Comment by njdu** [comment]
@bruceywang I added an uptime widget that simply tracks whether the UI test last passed or failed. 

However, because the UI Status Check test relies on a service external to Runscope, its json response is formatted a little differently than other tests - it doesn't include the timestamps when a particular step request is sent or  the response is received. This is how I calculated runtime on other tests

The response does have "finished_at" and "started_at" fields, but as we have seen in the past, these fields are not accurate to the actual runtime of the test
