### ISSUE TITLE
Add new Runscope tests on geckoboard

### ISSUE THREAD

**Issue by bruceywang** [Brightergy/ex_gecko#20]
We have new system tests and we want to track the success/failure of this as a widget.  We may want to use the datasets API instead to track a set of success/failures, or we can use the "UPTIME" but that one is not as descriptive.

**Comment by njdu** [comment]
Hey quick question, for the improved Runscope API widget, what kind of information would you like to see?

We have five different tests for each of the API categories, and I can show which steps failed/succeeded

**Comment by njdu** [comment]
My plan is to create a test result schema and define functions that store key metrics of the latest result within the schema. 

The Dataset could take the form of:

Test Name | Test Result | Failed Test Steps | Passing Test Steps | Average Response Time | Date of Test

This will require expanding out the runscope adapter a bit. Right now, the runscope adapter can only push data to specific widgets - it does not have the ability to push data to Geckoboard's new Datasets API

**Comment by bruceywang** [comment]
@njdu Yes, thats what I was thinking, use the datasets, and include the tests, and the results and speeds.  This way we can display it.  The only issue I see would be, lets say you have test 1 and test 2, and the run history for 8am, and 9am, it will show as 4 results, how would we show the successfulness?  Is it more like, whats the percentage of success in the last day or whatever?

**Comment by njdu** [comment]
@bruceywang Yeah, that's a good point. Rather than print out multiple results for a specific test, like:

Test 1 | 8 AM  | ....
Test 1 | 9 AM | ....

Maybe I can just try to replicate the Runscope dashboard:

[](https://www.runscope.com/radar/to5q0u5gglr4)

Each test has one entry in the table, we show how long ago the last test was, whether it was a success/failure, its response time, and the percentage of successes over the last N tests

**Comment by njdu** [comment]
@erik-jenkins So I realized I was going about this a bit wrong. As we know, the existing Runscope adapter that we are building off of only supports directly updating widgets, which is a Geckoboard legacy system where you provide a widget key, then push data to that widget. For this task, we want to use the new Dataset Api.

I had been thinking about how we would define a system where a user could get runscope data according to a previously defined schema format. However, I had been overlooking the details for the heroku and papertrail adapters. Looking at them today, I saw that they already have a system for defining a schema, and then pulling data according to that schema. You define what your data looks like in the datasets folder, and then specify what format you want as a gecko.load argument.

I went ahead and added a runscope.dash.json file that defines the proper schema for mimicking the runscope dashboard. I'm building out the runscope adapter to handle events build around this schema

**Comment by njdu** [comment]
@bruceywang. Completed through #24 . Sorry this took so long, I originally planned on making a single leaderboard widget with the same data that you see on the Runscope dashboard, but I didn't realize that Geckoboard leaderboards can only have two columns.

Anyway, the widgets that use the new Runscope datasets are at the bottom of the brightergy API page. Each API test on runscope gets three widgets, that track the success ratio over the past three days, the percentage of assertions passed over the last few tests, and the average response time of the test.

Unfortunately, you can't display a string statement on a widget, like a "Passing" or "Failing" status. So, to check whether or not the last test was passing, we just have to look at whether 100% of assertions passed.

**Comment by njdu** [comment]
@bruceywang @erik-jenkins Given that we had a limited amount of space available on the dashboard, I eventually ended up using the Uptime widget for each API test, rather than the datasets. I couldn't find any other way to display the average response time, the success of the test, and downtime more efficiently than the default uptime widget.

The geckoboard dataset widgets right now are somewhat limited in terms of display options. For example, I wanted to display the percentage of assertions for a test over time on a line chart, and have a series for each Runscope test on the same plot. However, you can't currently accomplish this on Geckoboard. You need to make a separate line chart for each test, which would take up way too much space.

The runscope dataset is still fully functional however, so hopefully as the Dataset options improve, we can make use of them
